  CREATE TABLE "MD_PROCESS_LOG" 
   (	"MSTR_LOG_ID" NUMBER NOT NULL ENABLE, 
	"LOG_ID" NUMBER NOT NULL ENABLE, 
	"LOG_CATEG" VARCHAR2(256), 
	"MSTR_FUN" VARCHAR2(128), 
	"LOG_STTUS" VARCHAR2(30) NOT NULL ENABLE, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"INTERVAL_TIME" INTERVAL DAY (2) TO SECOND (6) GENERATED ALWAYS AS (NUMTODSINTERVAL("END_DATE"-"START_DATE",'DAY')) VIRTUAL , 
	"LOG_MSG" CLOB NOT NULL ENABLE, 
	"LAST_ERR_CODE" VARCHAR2(30), 
	"LAST_ERR_DESC" VARCHAR2(256), 
	"INST_ID" NUMBER, 
	"SID" NUMBER, 
	"SERIAL#" NUMBER, 
	"CLIENT_INFO" VARCHAR2(128), 
	"MODULE" VARCHAR2(128), 
	"CRTN_DT" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"CRTN_BY" VARCHAR2(128) DEFAULT sys_context('USERENV','SESSION_USER') NOT NULL ENABLE, 
	"LAST_UPDT_DT" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"LAST_UPDT_BY" VARCHAR2(128) DEFAULT sys_context('USERENV','SESSION_USER') NOT NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("LOG_MSG") STORE AS SECUREFILE (
  ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
  PARTITION BY RANGE ("START_DATE") INTERVAL (NUMTOYMINTERVAL(1, 'MONTH')) 
 (PARTITION "P_START"  VALUES LESS THAN (TO_DATE(' 2024-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("LOG_MSG") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) )