  CREATE TABLE "TBS_REBUILD_RUN" 
   (	"RUN_ID" NUMBER NOT NULL ENABLE, 
	"RUN_TYPE" VARCHAR2(30) NOT NULL ENABLE, 
	"START_TIME" DATE, 
	"END_TIME" DATE, 
	"STATUS" VARCHAR2(20) NOT NULL ENABLE, 
	"OWNER_FILTER" VARCHAR2(4000), 
	"SOURCE_TABLESPACE" VARCHAR2(30), 
	"TARGET_TABLESPACE" VARCHAR2(30), 
	"PARALLEL_DEGREE" NUMBER, 
	"TOTAL_STEPS" NUMBER, 
	"STEPS_OK" NUMBER, 
	"STEPS_ERROR" NUMBER, 
	"CREATED_AT" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(128) NOT NULL ENABLE, 
	"UPDATED_AT" DATE, 
	"UPDATED_BY" VARCHAR2(128), 
	 CONSTRAINT "CHK_TBS_REBUILD_RUN_TYPE" CHECK (run_type IN ('PRIMARY','FIX_UNUSABLE','FIX_INVALID')) ENABLE, 
	 CONSTRAINT "CHK_TBS_REBUILD_RUN_STATUS" CHECK (status IN (
            'NEW','PLANNED','RUNNING',
            'FINISHED_OK','FINISHED_ERR'
        )) ENABLE, 
	 CONSTRAINT "PK_TBS_REBUILD_RUN" PRIMARY KEY ("RUN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"