  CREATE TABLE "TBS_REBUILD_RUN_STEPS" 
   (	"STEP_ID" NUMBER NOT NULL ENABLE, 
	"RUN_ID" NUMBER NOT NULL ENABLE, 
	"STEP_ORDER" NUMBER NOT NULL ENABLE, 
	"OWNER_NAME" VARCHAR2(128) NOT NULL ENABLE, 
	"OBJECT_NAME" VARCHAR2(128) NOT NULL ENABLE, 
	"OBJECT_TYPE" VARCHAR2(30) NOT NULL ENABLE, 
	"SEGMENT_TYPE" VARCHAR2(30), 
	"PARTITION_NAME" VARCHAR2(128), 
	"SUBPARTITION_NAME" VARCHAR2(128), 
	"OPERATION_TYPE" VARCHAR2(30) NOT NULL ENABLE, 
	"STEP_TYPE" VARCHAR2(30) NOT NULL ENABLE, 
	"ONLINE_FLAG" CHAR(1) NOT NULL ENABLE, 
	"DDL_TEXT" CLOB NOT NULL ENABLE, 
	"DDL_TEXT_ORIG_PARALLEL" CLOB, 
	"ROLLBACK_DDL_TEXT" CLOB, 
	"DDL_GENERATOR_NAME" VARCHAR2(128) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(20) NOT NULL ENABLE, 
	"ERROR_MESSAGE" VARCHAR2(4000), 
	"ATTEMPTS" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"STEP_START_TIME" DATE, 
	"STEP_END_TIME" DATE, 
	"EXECUTED_AT" DATE, 
	"CREATED_AT" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(128) NOT NULL ENABLE, 
	"UPDATED_AT" DATE, 
	"UPDATED_BY" VARCHAR2(128), 
	"ORIG_PARALLEL_DEGREE" VARCHAR2(30), 
	 CONSTRAINT "CHK_TBS_REBUILD_ONLINE_FLAG" CHECK (online_flag IN ('Y','N')) ENABLE, 
	 CONSTRAINT "CHK_TBS_REBUILD_STEP_STATUS" CHECK (status IN ('PENDING','RUNNING','OK','ERROR','SKIPPED')) ENABLE, 
	 CONSTRAINT "CHK_TBS_REBUILD_STEP_TYPE" CHECK (step_type IN ('PRIMARY','FIX_UNUSABLE','FIX_INVALID','MANUAL')) ENABLE, 
	 CONSTRAINT "CHK_TBS_REBUILD_ATTEMPTS" CHECK (attempts >= 0) ENABLE, 
	 CONSTRAINT "PK_TBS_REBUILD_RUN_STEPS" PRIMARY KEY ("STEP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_TBS_REBUILD_STEPS_RUN" FOREIGN KEY ("RUN_ID")
	  REFERENCES "TOMASZ"."TBS_REBUILD_RUN" ("RUN_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DDL_TEXT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("DDL_TEXT_ORIG_PARALLEL") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ROLLBACK_DDL_TEXT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))